name: "Install Dafny"
description: "Install a packaged release of Dafny"
branding:
  icon: check-circle
  color: green
inputs:
  dafny-version:
    description: "Dafny version to install"
    required: true
    default: "3.1.0"
runs:
  using: "composite"
  steps:
  - uses: actions/setup-dotnet@v4
    with:
      dotnet-version: '6.0.x'
  - uses: actions/setup-node@v4
    with:
      node-version: 16
  - run: |
      echo $INPUT_DAFNY_VERSION
      echo ${{ inputs.dafny-version }}
      node dist/index.js
    shell: bash
    env:
      INPUT_DAFNY_VERSION: ${{ inputs.dafny-version }}
