name: "Install Dafny"
description: "Install a packaged release of Dafny"
branding:
  icon: check-circle
  color: green
inputs:
  dafny-version:
    description: "Dafny version to install"
    required: true
  dafny-latest-nightly:
    description: "Whether to install the latest prerelease within the same major version"
    required: false
    default: "false"
runs:
  using: "node16"
  main: "dist/index.js"
